# Using postgres as the DB
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets.db_name %>
  pool: 5
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_pass %>

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default
